spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
    hibernate:
        ddl-auto: update
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/dev"
    username: "karthik"
    #password: "pw"
    password: "{cipher}6a97c04b4db090e4b0c6f49527ee4cbae1968392eb17da2fdca17088b54d587d"
    tomcat:
      test-while-idle: true
      validation-query: "SELECT 1"
security:
  basic:
    enabled: false
server:
  port: 8082
